### ISSUE TITLE
AttributeError: 'str' object has no attribute '_output_dir'

### ISSUE THREAD

**Issue by lakishadavid** [apriha/lineage#84]
I'm using aws ec2 ubuntu. It does not allow me to create an individual.

>>> user662 = l.create_individual('User662', '/home/ubuntu/myprojectdir/AaronAzuma.zip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/myprojectdir/venv/lib/python3.8/site-packages/lineage/__init__.py", line 96, in create_individual
    return Individual(name, raw_data, self._output_dir, **kwargs)
AttributeError: 'str' object has no attribute '_output_dir'

**Comment by apriha** [comment]
Thanks for the issue. Can you provide more details or code snippets? I just tested installing and running the `README` examples in a Python 3.8 virtual environment without any issues.

**Comment by lakishadavid** [comment]
Thanks Andrew,

On using your example data and the create_individual working, I realized
that my issue was with the parsing. I already converted the format from
AncestryDNA to 23andMe and then tried to use create_indidual. I receive the
parsing error, which then doesn't allow me to go forward. My other set of
files also have 4 columns like 23andMe but no headers (from the H3Africa
array with another lab).

$ sed -n 1,20p lineage/inputs/myfile.txt
#AncestryDNA raw data download
#This file was generated by AncestryDNA at: 07/31/2018 23:48:22 UTC
#Data was collected using AncestryDNA array version: V2.0
#Data is formatted using AncestryDNA converter version: V1.0
...
rsid    chromosome      position        allele1allele2
rs369202065     1       569388  GG

$ python manage.py shell
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux

>>> from lineage import Lineage
>>> l = Lineage()

>>> user111 = l.create_individual('User111', 'myfile.txt')
pandas.errors.ParserError: Too many columns specified: expected 5 and found
4

LaKisha
